---
- name: Update all packages
  ansible.builtin.apt:
    update_cache: yes
    name: "*"
    state: latest

- name: Install curl
  ansible.builtin.apt:
    name: "curl"
    state: present

- name: Install docker on a machine
  ansible.builtin.shell: curl -sSL https://get.docker.com/ | sudo sh

- name: Change privelege of docker
  ansible.builtin.command: chmod +x /usr/bin/docker