---
- name: Copy src files
  ansible.builtin.copy:
    src: src
    dest: /home/vagrant/sqlite
    owner: vagrant
    group: vagrant

- name: Create docker-out directory
  ansible.builtin.file:
    path: /home/vagrant/sqlite/src/docker-out
    state: directory

- name: Build the container
  ansible.builtin.shell: "docker build -t sqlite3cmp:latest /home/vagrant/sqlite/src/"

- name: Run the container
  ansible.builtin.shell: "docker run sqlite3cmp:latest"