---
- hosts: sqlite-cmp
  gather_facts: yes
  become: yes
  
  roles:
    - init
    - compile
- name: Create project directory
  ansible.builtin.file:
    path: /home/vagrant/sqlite/src
    state: directory

